# Generated by Django 4.0.5 on 2022-06-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('apply_date', models.DateField()),
                ('name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('device_place_location', models.CharField(max_length=300)),
                ('source_ip_address', models.GenericIPAddressField()),
                ('destination_ip_address', models.GenericIPAddressField()),
                ('open_direction', models.IntegerField()),
                ('protocols', models.CharField(max_length=10)),
                ('ports', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=300)),
                ('apply_during_begin', models.DateField()),
                ('apply_during_end', models.DateField()),
                ('declare', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
