# Generated by Django 4.0.5 on 2022-06-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_apply_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
